import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        white: "var(--ui-white)",
        "light-gray": "var(--ui-light-gray)",
        gray: "var(--ui-gray)",
        "dark-gray": "var(--ui-dark-gray)",
        black: "var(--ui-black)",
        primary: "var(--ui-primary)",
        error: "var(--ui-error)",
        bg: "var(--ui-bg)",
        nav: "var(--ui-nav)",
        "text-primary": "var(--ui-text-primary)",
        "text-secondary": "var(--ui-text-secondary)",
        "text-muted": "var(--ui-text-muted)",
        "border-strong": "var(--ui-border-strong)",
        "company-1-muted": "var(--ui-company-1-muted)",
        "company-1-intense": "var(--ui-company-1-intense)",
        "company-2-muted": "var(--ui-company-2-muted)",
        "company-2-intense": "var(--ui-company-2-intense)",
        "company-3-muted": "var(--ui-company-3-muted)",
        "company-3-intense": "var(--ui-company-3-intense)",
        "company-4-muted": "var(--ui-company-4-muted)",
        "company-4-intense": "var(--ui-company-4-intense)",
        "company-5-muted": "var(--ui-company-5-muted)",
        "company-5-intense": "var(--ui-company-5-intense)",
        "company-6-muted": "var(--ui-company-6-muted)",
        "company-6-intense": "var(--ui-company-6-intense)",
        "company-7-muted": "var(--ui-company-7-muted)",
        "company-7-intense": "var(--ui-company-7-intense)",
        "company-8-muted": "var(--ui-company-8-muted)",
        "company-8-intense": "var(--ui-company-8-intense)",
        "company-9-muted": "var(--ui-company-9-muted)",
        "company-9-intense": "var(--ui-company-9-intense)",
        "company-10-muted": "var(--ui-company-10-muted)",
        "company-10-intense": "var(--ui-company-10-intense)",
        "company-11-muted": "var(--ui-company-11-muted)",
        "company-11-intense": "var(--ui-company-11-intense)",
        "company-12-muted": "var(--ui-company-12-muted)",
        "company-12-intense": "var(--ui-company-12-intense)",
        surface: "var(--ui-surface)",
        "surface-raised": "var(--ui-surface-raised)",
        accent: "var(--ui-accent)",
        "accent-muted": "var(--ui-accent-muted)",
        border: "var(--ui-border)",
      },
    },
  },
  plugins: [],
};

export default config;
